version: '3.8'

services:
    
    
   
    homeinsurance:        
        build: OnlineInsurance
        ports:
        - 8009:8009
     
  

    postgres:        
        image: postgres:14.5
        ports:
        - 5432:5432
       
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pgadmin
            POSTGRES_DB: homedb
